# Generated by Django 5.0 on 2023-12-10 11:55

from django.db import migrations
from django.conf import settings


def forwards_func(apps, schema_editor):
    Site = apps.get_model("sites", "Site")
    site = Site.objects.get(id=settings.SITE_ID)
    FlatPage = apps.get_model("flatpages", "FlatPage")
    home = FlatPage.objects.create(
        url="/",
        title="Home page",
        content="",
        template_name="flatpages/home.html",
    )
    home.sites.add(site)
    home.save()


def reverse_func(apps, schema_editor):
    FlatPage = apps.get_model("flatpages", "FlatPage")
    FlatPage.objects.filter(url="/").delete()


class Migration(migrations.Migration):
    dependencies = [
        ("flatpages", "0001_initial"),
        ("sites", "0003_set_site_domain_and_name"),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
